-- Complete category import with 249 total categories
-- Clear existing data and insert new complete data
DELETE FROM marketplace_categories;

INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook', NULL, 2, 'kindle_ebook', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Affari e Finanza', 'Books > kindle_ebook', 3, 'Affari e Finanza', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Affari e Finanza > Imprenditoria', 'Books > kindle_ebook > Affari e Finanza', 4, 'Imprenditoria', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Affari e Finanza > Imprenditoria > Startup', 'Books > kindle_ebook > Affari e Finanza > Imprenditoria', 5, 'Startup', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Affari e Finanza > Imprenditoria > Startup > Raccolta fondi', 'Books > kindle_ebook > Affari e Finanza > Imprenditoria > Startup', 6, 'Raccolta fondi', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback', NULL, 2, 'print_kdp_paperback', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Affari e Finanza', 'Books > print_kdp_paperback', 3, 'Affari e Finanza', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Affari e Finanza > Imprenditoria', 'Books > print_kdp_paperback > Affari e Finanza', 4, 'Imprenditoria', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Affari e Finanza > Imprenditoria > Startup', 'Books > print_kdp_paperback > Affari e Finanza > Imprenditoria', 5, 'Startup', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Affari e Finanza > Imprenditoria > Startup > Raccolta fondi', 'Books > print_kdp_paperback > Affari e Finanza > Imprenditoria > Startup', 6, 'Raccolta fondi', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Bambini e Ragazzi', 'Books > kindle_ebook', 3, 'Bambini e Ragazzi', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Bambini e Ragazzi > Libri per bambini', 'Books > kindle_ebook > Bambini e Ragazzi', 4, 'Libri per bambini', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Bambini e Ragazzi > Libri per bambini > Libri illustrati', 'Books > kindle_ebook > Bambini e Ragazzi > Libri per bambini', 5, 'Libri illustrati', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Bambini e Ragazzi > Libri per bambini > Libri illustrati > Animali', 'Books > kindle_ebook > Bambini e Ragazzi > Libri per bambini > Libri illustrati', 6, 'Animali', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Bambini e Ragazzi', 'Books > print_kdp_paperback', 3, 'Bambini e Ragazzi', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Bambini e Ragazzi > Libri per bambini', 'Books > print_kdp_paperback > Bambini e Ragazzi', 4, 'Libri per bambini', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Bambini e Ragazzi > Libri per bambini > Libri illustrati', 'Books > print_kdp_paperback > Bambini e Ragazzi > Libri per bambini', 5, 'Libri illustrati', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Bambini e Ragazzi > Libri per bambini > Libri illustrati > Animali', 'Books > print_kdp_paperback > Bambini e Ragazzi > Libri per bambini > Libri illustrati', 6, 'Animali', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback', NULL, 2, 'print_kdp_paperback', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Business & Finance', 'Books > print_kdp_paperback', 3, 'Business & Finance', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Business & Finance > Entrepreneurship', 'Books > print_kdp_paperback > Business & Finance', 4, 'Entrepreneurship', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Business & Finance > Entrepreneurship > Startups', 'Books > print_kdp_paperback > Business & Finance > Entrepreneurship', 5, 'Startups', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Business & Finance > Entrepreneurship > Startups > Fundraising', 'Books > print_kdp_paperback > Business & Finance > Entrepreneurship > Startups', 6, 'Fundraising', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook', NULL, 2, 'kindle_ebook', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Business & Finance', 'Books > kindle_ebook', 3, 'Business & Finance', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Business & Finance > Entrepreneurship', 'Books > kindle_ebook > Business & Finance', 4, 'Entrepreneurship', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Business & Finance > Entrepreneurship > Startups', 'Books > kindle_ebook > Business & Finance > Entrepreneurship', 5, 'Startups', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Business & Finance > Entrepreneurship > Startups > Fundraising', 'Books > kindle_ebook > Business & Finance > Entrepreneurship > Startups', 6, 'Fundraising', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook', NULL, 2, 'kindle_ebook', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Bücher & Literatur', 'Books > kindle_ebook', 3, 'Bücher & Literatur', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Bücher & Literatur > Fantasy', 'Books > kindle_ebook > Bücher & Literatur', 4, 'Fantasy', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Bücher & Literatur > Fantasy > High Fantasy', 'Books > kindle_ebook > Bücher & Literatur > Fantasy', 5, 'High Fantasy', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Bücher & Literatur > Fantasy > High Fantasy > Episch', 'Books > kindle_ebook > Bücher & Literatur > Fantasy > High Fantasy', 6, 'Episch', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Bücher & Literatur > Fantasy > High Fantasy > Episch > Mittelalterlich', 'Books > kindle_ebook > Bücher & Literatur > Fantasy > High Fantasy > Episch', 7, 'Mittelalterlich', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback', NULL, 2, 'print_kdp_paperback', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Bücher & Literatur', 'Books > print_kdp_paperback', 3, 'Bücher & Literatur', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Bücher & Literatur > Fantasy', 'Books > print_kdp_paperback > Bücher & Literatur', 4, 'Fantasy', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Bücher & Literatur > Fantasy > High Fantasy', 'Books > print_kdp_paperback > Bücher & Literatur > Fantasy', 5, 'High Fantasy', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Bücher & Literatur > Fantasy > High Fantasy > Episch', 'Books > print_kdp_paperback > Bücher & Literatur > Fantasy > High Fantasy', 6, 'Episch', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Bücher & Literatur > Fantasy > High Fantasy > Episch > Mittelalterlich', 'Books > print_kdp_paperback > Bücher & Literatur > Fantasy > High Fantasy > Episch', 7, 'Mittelalterlich', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Children & Teens', 'Books > print_kdp_paperback', 3, 'Children & Teens', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Children & Teens > Children''s Books', 'Books > print_kdp_paperback > Children & Teens', 4, 'Children''s Books', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Children & Teens > Children''s Books > Picture Books', 'Books > print_kdp_paperback > Children & Teens > Children''s Books', 5, 'Picture Books', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Children & Teens > Children''s Books > Picture Books > Animals', 'Books > print_kdp_paperback > Children & Teens > Children''s Books > Picture Books', 6, 'Animals', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Children & Teens', 'Books > kindle_ebook', 3, 'Children & Teens', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Children & Teens > Children''s Books', 'Books > kindle_ebook > Children & Teens', 4, 'Children''s Books', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Children & Teens > Children''s Books > Picture Books', 'Books > kindle_ebook > Children & Teens > Children''s Books', 5, 'Picture Books', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Children & Teens > Children''s Books > Picture Books > Animals', 'Books > kindle_ebook > Children & Teens > Children''s Books > Picture Books', 6, 'Animals', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook', NULL, 2, 'kindle_ebook', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Ciencia, Tecnología y Medicina', 'Books > kindle_ebook', 3, 'Ciencia, Tecnología y Medicina', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Ciencia, Tecnología y Medicina > Informática', 'Books > kindle_ebook > Ciencia, Tecnología y Medicina', 4, 'Informática', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Ciencia, Tecnología y Medicina > Informática > Programación', 'Books > kindle_ebook > Ciencia, Tecnología y Medicina > Informática', 5, 'Programación', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Ciencia, Tecnología y Medicina > Informática > Programación > Python', 'Books > kindle_ebook > Ciencia, Tecnología y Medicina > Informática > Programación', 6, 'Python', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Ciencia, Tecnología y Medicina > Informática > Programación > Python > Ciencia de datos', 'Books > kindle_ebook > Ciencia, Tecnología y Medicina > Informática > Programación > Python', 7, 'Ciencia de datos', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback', NULL, 2, 'print_kdp_paperback', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Ciencia, Tecnología y Medicina', 'Books > print_kdp_paperback', 3, 'Ciencia, Tecnología y Medicina', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Ciencia, Tecnología y Medicina > Informática', 'Books > print_kdp_paperback > Ciencia, Tecnología y Medicina', 4, 'Informática', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Ciencia, Tecnología y Medicina > Informática > Programación', 'Books > print_kdp_paperback > Ciencia, Tecnología y Medicina > Informática', 5, 'Programación', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Ciencia, Tecnología y Medicina > Informática > Programación > Python', 'Books > print_kdp_paperback > Ciencia, Tecnología y Medicina > Informática > Programación', 6, 'Python', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Ciencia, Tecnología y Medicina > Informática > Programación > Python > Ciencia de datos', 'Books > print_kdp_paperback > Ciencia, Tecnología y Medicina > Informática > Programación > Python', 7, 'Ciencia de datos', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback', NULL, 2, 'print_kdp_paperback', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Enfants & Adolescents', 'Books > print_kdp_paperback', 3, 'Enfants & Adolescents', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Enfants & Adolescents > Livres pour enfants', 'Books > print_kdp_paperback > Enfants & Adolescents', 4, 'Livres pour enfants', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Enfants & Adolescents > Livres pour enfants > Albums illustrés', 'Books > print_kdp_paperback > Enfants & Adolescents > Livres pour enfants', 5, 'Albums illustrés', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Enfants & Adolescents > Livres pour enfants > Albums illustrés > Animaux', 'Books > print_kdp_paperback > Enfants & Adolescents > Livres pour enfants > Albums illustrés', 6, 'Animaux', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook', NULL, 2, 'kindle_ebook', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Enfants & Adolescents', 'Books > kindle_ebook', 3, 'Enfants & Adolescents', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Enfants & Adolescents > Livres pour enfants', 'Books > kindle_ebook > Enfants & Adolescents', 4, 'Livres pour enfants', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Enfants & Adolescents > Livres pour enfants > Albums illustrés', 'Books > kindle_ebook > Enfants & Adolescents > Livres pour enfants', 5, 'Albums illustrés', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Enfants & Adolescents > Livres pour enfants > Albums illustrés > Animaux', 'Books > kindle_ebook > Enfants & Adolescents > Livres pour enfants > Albums illustrés', 6, 'Animaux', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Entreprise & Bourse', 'Books > print_kdp_paperback', 3, 'Entreprise & Bourse', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Entreprise & Bourse > Entrepreneuriat', 'Books > print_kdp_paperback > Entreprise & Bourse', 4, 'Entrepreneuriat', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Entreprise & Bourse > Entrepreneuriat > Start-up', 'Books > print_kdp_paperback > Entreprise & Bourse > Entrepreneuriat', 5, 'Start-up', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Entreprise & Bourse > Entrepreneuriat > Start-up > Levée de fonds', 'Books > print_kdp_paperback > Entreprise & Bourse > Entrepreneuriat > Start-up', 6, 'Levée de fonds', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Entreprise & Bourse', 'Books > kindle_ebook', 3, 'Entreprise & Bourse', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Entreprise & Bourse > Entrepreneuriat', 'Books > kindle_ebook > Entreprise & Bourse', 4, 'Entrepreneuriat', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Entreprise & Bourse > Entrepreneuriat > Start-up', 'Books > kindle_ebook > Entreprise & Bourse > Entrepreneuriat', 5, 'Start-up', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Entreprise & Bourse > Entrepreneuriat > Start-up > Levée de fonds', 'Books > kindle_ebook > Entreprise & Bourse > Entrepreneuriat > Start-up', 6, 'Levée de fonds', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Guide & Conseils', 'Books > kindle_ebook', 3, 'Guide & Conseils', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Guide & Conseils > Bien-être', 'Books > kindle_ebook > Guide & Conseils', 4, 'Bien-être', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Guide & Conseils > Bien-être > Méditation', 'Books > kindle_ebook > Guide & Conseils > Bien-être', 5, 'Méditation', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Guide & Conseils > Bien-être > Méditation > Pleine conscience', 'Books > kindle_ebook > Guide & Conseils > Bien-être > Méditation', 6, 'Pleine conscience', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Guide & Conseils > Bien-être > Méditation > Pleine conscience > Yoga', 'Books > kindle_ebook > Guide & Conseils > Bien-être > Méditation > Pleine conscience', 7, 'Yoga', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Guide & Conseils > Bien-être > Méditation > Pleine conscience > Yoga > Yoga sur chaise', 'Books > kindle_ebook > Guide & Conseils > Bien-être > Méditation > Pleine conscience > Yoga', 8, 'Yoga sur chaise', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Guide & Conseils', 'Books > print_kdp_paperback', 3, 'Guide & Conseils', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Guide & Conseils > Bien-être', 'Books > print_kdp_paperback > Guide & Conseils', 4, 'Bien-être', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Guide & Conseils > Bien-être > Méditation', 'Books > print_kdp_paperback > Guide & Conseils > Bien-être', 5, 'Méditation', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Guide & Conseils > Bien-être > Méditation > Pleine conscience', 'Books > print_kdp_paperback > Guide & Conseils > Bien-être > Méditation', 6, 'Pleine conscience', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Guide & Conseils > Bien-être > Méditation > Pleine conscience > Yoga', 'Books > print_kdp_paperback > Guide & Conseils > Bien-être > Méditation > Pleine conscience', 7, 'Yoga', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Guide e Consigli', 'Books > kindle_ebook', 3, 'Guide e Consigli', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Guide e Consigli > Benessere', 'Books > kindle_ebook > Guide e Consigli', 4, 'Benessere', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Guide e Consigli > Benessere > Meditazione', 'Books > kindle_ebook > Guide e Consigli > Benessere', 5, 'Meditazione', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Guide e Consigli > Benessere > Meditazione > Consapevolezza', 'Books > kindle_ebook > Guide e Consigli > Benessere > Meditazione', 6, 'Consapevolezza', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Guide e Consigli > Benessere > Meditazione > Consapevolezza > Yoga', 'Books > kindle_ebook > Guide e Consigli > Benessere > Meditazione > Consapevolezza', 7, 'Yoga', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Guide e Consigli', 'Books > print_kdp_paperback', 3, 'Guide e Consigli', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Guide e Consigli > Benessere', 'Books > print_kdp_paperback > Guide e Consigli', 4, 'Benessere', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Guide e Consigli > Benessere > Meditazione', 'Books > print_kdp_paperback > Guide e Consigli > Benessere', 5, 'Meditazione', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Guide e Consigli > Benessere > Meditazione > Consapevolezza', 'Books > print_kdp_paperback > Guide e Consigli > Benessere > Meditazione', 6, 'Consapevolezza', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Guide e Consigli > Benessere > Meditazione > Consapevolezza > Yoga', 'Books > print_kdp_paperback > Guide e Consigli > Benessere > Meditazione > Consapevolezza', 7, 'Yoga', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Guides & Advice', 'Books > kindle_ebook', 3, 'Guides & Advice', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Guides & Advice > Wellness', 'Books > kindle_ebook > Guides & Advice', 4, 'Wellness', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Guides & Advice > Wellness > Meditation', 'Books > kindle_ebook > Guides & Advice > Wellness', 5, 'Meditation', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Guides & Advice > Wellness > Meditation > Mindfulness', 'Books > kindle_ebook > Guides & Advice > Wellness > Meditation', 6, 'Mindfulness', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Guides & Advice > Wellness > Meditation > Mindfulness > Yoga', 'Books > kindle_ebook > Guides & Advice > Wellness > Meditation > Mindfulness', 7, 'Yoga', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Guides & Advice', 'Books > print_kdp_paperback', 3, 'Guides & Advice', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Guides & Advice > Wellness', 'Books > print_kdp_paperback > Guides & Advice', 4, 'Wellness', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Guides & Advice > Wellness > Meditation', 'Books > print_kdp_paperback > Guides & Advice > Wellness', 5, 'Meditation', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Guides & Advice > Wellness > Meditation > Mindfulness', 'Books > print_kdp_paperback > Guides & Advice > Wellness > Meditation', 6, 'Mindfulness', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Guides & Advice > Wellness > Meditation > Mindfulness > Yoga', 'Books > print_kdp_paperback > Guides & Advice > Wellness > Meditation > Mindfulness', 7, 'Yoga', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Guías y Consejos', 'Books > kindle_ebook', 3, 'Guías y Consejos', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Guías y Consejos > Bienestar', 'Books > kindle_ebook > Guías y Consejos', 4, 'Bienestar', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Guías y Consejos > Bienestar > Meditación', 'Books > kindle_ebook > Guías y Consejos > Bienestar', 5, 'Meditación', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Guías y Consejos > Bienestar > Meditación > Atención plena', 'Books > kindle_ebook > Guías y Consejos > Bienestar > Meditación', 6, 'Atención plena', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Guías y Consejos > Bienestar > Meditación > Atención plena > Yoga', 'Books > kindle_ebook > Guías y Consejos > Bienestar > Meditación > Atención plena', 7, 'Yoga', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Guías y Consejos', 'Books > print_kdp_paperback', 3, 'Guías y Consejos', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Guías y Consejos > Bienestar', 'Books > print_kdp_paperback > Guías y Consejos', 4, 'Bienestar', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Guías y Consejos > Bienestar > Meditación', 'Books > print_kdp_paperback > Guías y Consejos > Bienestar', 5, 'Meditación', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Guías y Consejos > Bienestar > Meditación > Atención plena', 'Books > print_kdp_paperback > Guías y Consejos > Bienestar > Meditación', 6, 'Atención plena', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Guías y Consejos > Bienestar > Meditación > Atención plena > Yoga', 'Books > print_kdp_paperback > Guías y Consejos > Bienestar > Meditación > Atención plena', 7, 'Yoga', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Infantil y Juvenil', 'Books > kindle_ebook', 3, 'Infantil y Juvenil', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Infantil y Juvenil > Libros infantiles', 'Books > kindle_ebook > Infantil y Juvenil', 4, 'Libros infantiles', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Infantil y Juvenil > Libros infantiles > Libros ilustrados', 'Books > kindle_ebook > Infantil y Juvenil > Libros infantiles', 5, 'Libros ilustrados', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Infantil y Juvenil > Libros infantiles > Libros ilustrados > Animales', 'Books > kindle_ebook > Infantil y Juvenil > Libros infantiles > Libros ilustrados', 6, 'Animales', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Infantil y Juvenil', 'Books > print_kdp_paperback', 3, 'Infantil y Juvenil', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Infantil y Juvenil > Libros infantiles', 'Books > print_kdp_paperback > Infantil y Juvenil', 4, 'Libros infantiles', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Infantil y Juvenil > Libros infantiles > Libros ilustrados', 'Books > print_kdp_paperback > Infantil y Juvenil > Libros infantiles', 5, 'Libros ilustrados', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Infantil y Juvenil > Libros infantiles > Libros ilustrados > Animales', 'Books > print_kdp_paperback > Infantil y Juvenil > Libros infantiles > Libros ilustrados', 6, 'Animales', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Kinder & Jugendbücher', 'Books > kindle_ebook', 3, 'Kinder & Jugendbücher', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Kinder & Jugendbücher > Kinderbücher', 'Books > kindle_ebook > Kinder & Jugendbücher', 4, 'Kinderbücher', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Kinder & Jugendbücher > Kinderbücher > Bilderbücher', 'Books > kindle_ebook > Kinder & Jugendbücher > Kinderbücher', 5, 'Bilderbücher', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Kinder & Jugendbücher > Kinderbücher > Bilderbücher > Tiere', 'Books > kindle_ebook > Kinder & Jugendbücher > Kinderbücher > Bilderbücher', 6, 'Tiere', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Kinder & Jugendbücher', 'Books > print_kdp_paperback', 3, 'Kinder & Jugendbücher', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Kinder & Jugendbücher > Kinderbücher', 'Books > print_kdp_paperback > Kinder & Jugendbücher', 4, 'Kinderbücher', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Kinder & Jugendbücher > Kinderbücher > Bilderbücher', 'Books > print_kdp_paperback > Kinder & Jugendbücher > Kinderbücher', 5, 'Bilderbücher', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Kinder & Jugendbücher > Kinderbücher > Bilderbücher > Tiere', 'Books > print_kdp_paperback > Kinder & Jugendbücher > Kinderbücher > Bilderbücher', 6, 'Tiere', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Libri e Letteratura', 'Books > print_kdp_paperback', 3, 'Libri e Letteratura', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Libri e Letteratura > Fantasy', 'Books > print_kdp_paperback > Libri e Letteratura', 4, 'Fantasy', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Libri e Letteratura > Fantasy > High Fantasy', 'Books > print_kdp_paperback > Libri e Letteratura > Fantasy', 5, 'High Fantasy', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Libri e Letteratura > Fantasy > High Fantasy > Epico', 'Books > print_kdp_paperback > Libri e Letteratura > Fantasy > High Fantasy', 6, 'Epico', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Libri e Letteratura > Fantasy > High Fantasy > Epico > Medievale', 'Books > print_kdp_paperback > Libri e Letteratura > Fantasy > High Fantasy > Epico', 7, 'Medievale', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Libri e Letteratura', 'Books > kindle_ebook', 3, 'Libri e Letteratura', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Libri e Letteratura > Fantasy', 'Books > kindle_ebook > Libri e Letteratura', 4, 'Fantasy', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Libri e Letteratura > Fantasy > High Fantasy', 'Books > kindle_ebook > Libri e Letteratura > Fantasy', 5, 'High Fantasy', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Libri e Letteratura > Fantasy > High Fantasy > Epico', 'Books > kindle_ebook > Libri e Letteratura > Fantasy > High Fantasy', 6, 'Epico', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Libri e Letteratura > Fantasy > High Fantasy > Epico > Medievale', 'Books > kindle_ebook > Libri e Letteratura > Fantasy > High Fantasy > Epico', 7, 'Medievale', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Libros y Literatura', 'Books > print_kdp_paperback', 3, 'Libros y Literatura', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Libros y Literatura > Fantasía', 'Books > print_kdp_paperback > Libros y Literatura', 4, 'Fantasía', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Libros y Literatura > Fantasía > Alta fantasía', 'Books > print_kdp_paperback > Libros y Literatura > Fantasía', 5, 'Alta fantasía', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Libros y Literatura > Fantasía > Alta fantasía > Épica', 'Books > print_kdp_paperback > Libros y Literatura > Fantasía > Alta fantasía', 6, 'Épica', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Libros y Literatura > Fantasía > Alta fantasía > Épica > Medieval', 'Books > print_kdp_paperback > Libros y Literatura > Fantasía > Alta fantasía > Épica', 7, 'Medieval', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Libros y Literatura', 'Books > kindle_ebook', 3, 'Libros y Literatura', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Libros y Literatura > Fantasía', 'Books > kindle_ebook > Libros y Literatura', 4, 'Fantasía', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Libros y Literatura > Fantasía > Alta fantasía', 'Books > kindle_ebook > Libros y Literatura > Fantasía', 5, 'Alta fantasía', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Libros y Literatura > Fantasía > Alta fantasía > Épica', 'Books > kindle_ebook > Libros y Literatura > Fantasía > Alta fantasía', 6, 'Épica', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Libros y Literatura > Fantasía > Alta fantasía > Épica > Medieval', 'Books > kindle_ebook > Libros y Literatura > Fantasía > Alta fantasía > Épica', 7, 'Medieval', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Literature & Fiction', 'Books > print_kdp_paperback', 3, 'Literature & Fiction', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Literature & Fiction > Fantasy', 'Books > print_kdp_paperback > Literature & Fiction', 4, 'Fantasy', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Literature & Fiction > Fantasy > High Fantasy', 'Books > print_kdp_paperback > Literature & Fiction > Fantasy', 5, 'High Fantasy', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Literature & Fiction > Fantasy > High Fantasy > Epic', 'Books > print_kdp_paperback > Literature & Fiction > Fantasy > High Fantasy', 6, 'Epic', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Literature & Fiction > Fantasy > High Fantasy > Epic > Medieval', 'Books > print_kdp_paperback > Literature & Fiction > Fantasy > High Fantasy > Epic', 7, 'Medieval', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Literature & Fiction', 'Books > kindle_ebook', 3, 'Literature & Fiction', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Literature & Fiction > Fantasy', 'Books > kindle_ebook > Literature & Fiction', 4, 'Fantasy', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Literature & Fiction > Fantasy > High Fantasy', 'Books > kindle_ebook > Literature & Fiction > Fantasy', 5, 'High Fantasy', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Literature & Fiction > Fantasy > High Fantasy > Epic', 'Books > kindle_ebook > Literature & Fiction > Fantasy > High Fantasy', 6, 'Epic', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Literature & Fiction > Fantasy > High Fantasy > Epic > Medieval', 'Books > kindle_ebook > Literature & Fiction > Fantasy > High Fantasy > Epic', 7, 'Medieval', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Littérature & Fiction', 'Books > print_kdp_paperback', 3, 'Littérature & Fiction', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Littérature & Fiction > Fantasy', 'Books > print_kdp_paperback > Littérature & Fiction', 4, 'Fantasy', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Littérature & Fiction > Fantasy > High Fantasy2', 'Books > print_kdp_paperback > Littérature & Fiction > Fantasy', 5, 'High Fantasy2', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Littérature & Fiction > Fantasy > High Fantasy2 > Épique', 'Books > print_kdp_paperback > Littérature & Fiction > Fantasy > High Fantasy2', 6, 'Épique', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Littérature & Fiction > Fantasy > High Fantasy2 > Épique > Médiéval', 'Books > print_kdp_paperback > Littérature & Fiction > Fantasy > High Fantasy2 > Épique', 7, 'Médiéval', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Littérature & Fiction', 'Books > kindle_ebook', 3, 'Littérature & Fiction', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Littérature & Fiction > Roman', 'Books > kindle_ebook > Littérature & Fiction', 4, 'Roman', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Littérature & Fiction > Roman > Amour', 'Books > kindle_ebook > Littérature & Fiction > Roman', 5, 'Amour', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Littérature & Fiction > Roman > Amour > Épique', 'Books > kindle_ebook > Littérature & Fiction > Roman > Amour', 6, 'Épique', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Littérature & Fiction > Roman > Amour > Épique > Médiéval', 'Books > kindle_ebook > Littérature & Fiction > Roman > Amour > Épique', 7, 'Médiéval', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Littérature & Fiction > Roman > Amour > Épique > Médiéval > Tip', 'Books > kindle_ebook > Littérature & Fiction > Roman > Amour > Épique > Médiéval', 8, 'Tip', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Littérature & Fiction > Roman > Amour > Épique > Médiéval > Tip > Top', 'Books > kindle_ebook > Littérature & Fiction > Roman > Amour > Épique > Médiéval > Tip', 9, 'Top', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Littérature & Fiction > Roman > Amour > Épique > Médiéval > Tip > Top > Cool', 'Books > kindle_ebook > Littérature & Fiction > Roman > Amour > Épique > Médiéval > Tip > Top', 10, 'Cool', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Littérature & Fiction > Roman > Amour > Épique > Médiéval > Tip > Top > Cool > Moule', 'Books > kindle_ebook > Littérature & Fiction > Roman > Amour > Épique > Médiéval > Tip > Top > Cool', 11, 'Moule', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Littérature & Fiction > Fantasy', 'Books > kindle_ebook > Littérature & Fiction', 4, 'Fantasy', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Littérature & Fiction > Fantasy > High Fantasy', 'Books > kindle_ebook > Littérature & Fiction > Fantasy', 5, 'High Fantasy', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Littérature & Fiction > Fantasy > High Fantasy > Épique', 'Books > kindle_ebook > Littérature & Fiction > Fantasy > High Fantasy', 6, 'Épique', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Littérature & Fiction > Fantasy > High Fantasy > Épique > Médiéval', 'Books > kindle_ebook > Littérature & Fiction > Fantasy > High Fantasy > Épique', 7, 'Médiéval', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Negocios y Finanzas', 'Books > print_kdp_paperback', 3, 'Negocios y Finanzas', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Negocios y Finanzas > Emprendimiento', 'Books > print_kdp_paperback > Negocios y Finanzas', 4, 'Emprendimiento', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Negocios y Finanzas > Emprendimiento > Startups', 'Books > print_kdp_paperback > Negocios y Finanzas > Emprendimiento', 5, 'Startups', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > print_kdp_paperback > Negocios y Finanzas > Emprendimiento > Startups > Recaudación de fondos', 'Books > print_kdp_paperback > Negocios y Finanzas > Emprendimiento > Startups', 6, 'Recaudación de fondos', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Negocios y Finanzas', 'Books > kindle_ebook', 3, 'Negocios y Finanzas', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Negocios y Finanzas > Emprendimiento', 'Books > kindle_ebook > Negocios y Finanzas', 4, 'Emprendimiento', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Negocios y Finanzas > Emprendimiento > Startups', 'Books > kindle_ebook > Negocios y Finanzas > Emprendimiento', 5, 'Startups', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.es', 'Books > kindle_ebook > Negocios y Finanzas > Emprendimiento > Startups > Recaudación de fondos', 'Books > kindle_ebook > Negocios y Finanzas > Emprendimiento > Startups', 6, 'Recaudación de fondos', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Ratgeber & Tipps', 'Books > kindle_ebook', 3, 'Ratgeber & Tipps', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Ratgeber & Tipps > Wellness', 'Books > kindle_ebook > Ratgeber & Tipps', 4, 'Wellness', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Ratgeber & Tipps > Wellness > Meditation', 'Books > kindle_ebook > Ratgeber & Tipps > Wellness', 5, 'Meditation', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Ratgeber & Tipps > Wellness > Meditation > Achtsamkeit', 'Books > kindle_ebook > Ratgeber & Tipps > Wellness > Meditation', 6, 'Achtsamkeit', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Ratgeber & Tipps > Wellness > Meditation > Achtsamkeit > Yoga', 'Books > kindle_ebook > Ratgeber & Tipps > Wellness > Meditation > Achtsamkeit', 7, 'Yoga', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Ratgeber & Tipps', 'Books > print_kdp_paperback', 3, 'Ratgeber & Tipps', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Ratgeber & Tipps > Wellness', 'Books > print_kdp_paperback > Ratgeber & Tipps', 4, 'Wellness', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Ratgeber & Tipps > Wellness > Meditation', 'Books > print_kdp_paperback > Ratgeber & Tipps > Wellness', 5, 'Meditation', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Ratgeber & Tipps > Wellness > Meditation > Achtsamkeit', 'Books > print_kdp_paperback > Ratgeber & Tipps > Wellness > Meditation', 6, 'Achtsamkeit', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Ratgeber & Tipps > Wellness > Meditation > Achtsamkeit > Yoga', 'Books > print_kdp_paperback > Ratgeber & Tipps > Wellness > Meditation > Achtsamkeit', 7, 'Yoga', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Science, Tech & Medical', 'Books > print_kdp_paperback', 3, 'Science, Tech & Medical', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Science, Tech & Medical > Computers & Technology', 'Books > print_kdp_paperback > Science, Tech & Medical', 4, 'Computers & Technology', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Science, Tech & Medical > Computers & Technology > Programming', 'Books > print_kdp_paperback > Science, Tech & Medical > Computers & Technology', 5, 'Programming', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Science, Tech & Medical > Computers & Technology > Programming > Python', 'Books > print_kdp_paperback > Science, Tech & Medical > Computers & Technology > Programming', 6, 'Python', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Science, Tech & Medical > Computers & Technology > Programming > Python > Data Science', 'Books > print_kdp_paperback > Science, Tech & Medical > Computers & Technology > Programming > Python', 7, 'Data Science', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Science, Tech & Medical', 'Books > kindle_ebook', 3, 'Science, Tech & Medical', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Science, Tech & Medical > Computers & Technology', 'Books > kindle_ebook > Science, Tech & Medical', 4, 'Computers & Technology', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Science, Tech & Medical > Computers & Technology > Programming', 'Books > kindle_ebook > Science, Tech & Medical > Computers & Technology', 5, 'Programming', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Science, Tech & Medical > Computers & Technology > Programming > Python', 'Books > kindle_ebook > Science, Tech & Medical > Computers & Technology > Programming', 6, 'Python', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Science, Tech & Medical > Computers & Technology > Programming > Python > Data Science', 'Books > kindle_ebook > Science, Tech & Medical > Computers & Technology > Programming > Python', 7, 'Data Science', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Sciences, Techniques & Médecine', 'Books > print_kdp_paperback', 3, 'Sciences, Techniques & Médecine', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Sciences, Techniques & Médecine > Informatique', 'Books > print_kdp_paperback > Sciences, Techniques & Médecine', 4, 'Informatique', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Sciences, Techniques & Médecine > Informatique > Programmation', 'Books > print_kdp_paperback > Sciences, Techniques & Médecine > Informatique', 5, 'Programmation', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Sciences, Techniques & Médecine > Informatique > Programmation > Python', 'Books > print_kdp_paperback > Sciences, Techniques & Médecine > Informatique > Programmation', 6, 'Python', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Sciences, Techniques & Médecine > Informatique > Programmation > Python > Data Science', 'Books > print_kdp_paperback > Sciences, Techniques & Médecine > Informatique > Programmation > Python', 7, 'Data Science', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Sciences, Techniques & Médecine', 'Books > kindle_ebook', 3, 'Sciences, Techniques & Médecine', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Sciences, Techniques & Médecine > Informatique', 'Books > kindle_ebook > Sciences, Techniques & Médecine', 4, 'Informatique', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Sciences, Techniques & Médecine > Informatique > Programmation', 'Books > kindle_ebook > Sciences, Techniques & Médecine > Informatique', 5, 'Programmation', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Sciences, Techniques & Médecine > Informatique > Programmation > Python', 'Books > kindle_ebook > Sciences, Techniques & Médecine > Informatique > Programmation', 6, 'Python', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Sciences, Techniques & Médecine > Informatique > Programmation > Python > Data Science', 'Books > kindle_ebook > Sciences, Techniques & Médecine > Informatique > Programmation > Python', 7, 'Data Science', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Scienza, Tecnologia e Medicina', 'Books > kindle_ebook', 3, 'Scienza, Tecnologia e Medicina', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Scienza, Tecnologia e Medicina > Informatica', 'Books > kindle_ebook > Scienza, Tecnologia e Medicina', 4, 'Informatica', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Scienza, Tecnologia e Medicina > Informatica > Programmazione', 'Books > kindle_ebook > Scienza, Tecnologia e Medicina > Informatica', 5, 'Programmazione', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Scienza, Tecnologia e Medicina > Informatica > Programmazione > Python', 'Books > kindle_ebook > Scienza, Tecnologia e Medicina > Informatica > Programmazione', 6, 'Python', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > kindle_ebook > Scienza, Tecnologia e Medicina > Informatica > Programmazione > Python > Data Science', 'Books > kindle_ebook > Scienza, Tecnologia e Medicina > Informatica > Programmazione > Python', 7, 'Data Science', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Scienza, Tecnologia e Medicina', 'Books > print_kdp_paperback', 3, 'Scienza, Tecnologia e Medicina', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Scienza, Tecnologia e Medicina > Informatica', 'Books > print_kdp_paperback > Scienza, Tecnologia e Medicina', 4, 'Informatica', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Scienza, Tecnologia e Medicina > Informatica > Programmazione', 'Books > print_kdp_paperback > Scienza, Tecnologia e Medicina > Informatica', 5, 'Programmazione', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Scienza, Tecnologia e Medicina > Informatica > Programmazione > Python', 'Books > print_kdp_paperback > Scienza, Tecnologia e Medicina > Informatica > Programmazione', 6, 'Python', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.it', 'Books > print_kdp_paperback > Scienza, Tecnologia e Medicina > Informatica > Programmazione > Python > Data Science', 'Books > print_kdp_paperback > Scienza, Tecnologia e Medicina > Informatica > Programmazione > Python', 7, 'Data Science', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Wirtschaft & Finanzen', 'Books > print_kdp_paperback', 3, 'Wirtschaft & Finanzen', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Wirtschaft & Finanzen > Unternehmertum', 'Books > print_kdp_paperback > Wirtschaft & Finanzen', 4, 'Unternehmertum', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Wirtschaft & Finanzen > Unternehmertum > Startups', 'Books > print_kdp_paperback > Wirtschaft & Finanzen > Unternehmertum', 5, 'Startups', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Wirtschaft & Finanzen > Unternehmertum > Startups > Finanzierung', 'Books > print_kdp_paperback > Wirtschaft & Finanzen > Unternehmertum > Startups', 6, 'Finanzierung', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Wirtschaft & Finanzen', 'Books > kindle_ebook', 3, 'Wirtschaft & Finanzen', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Wirtschaft & Finanzen > Unternehmertum', 'Books > kindle_ebook > Wirtschaft & Finanzen', 4, 'Unternehmertum', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Wirtschaft & Finanzen > Unternehmertum > Startups', 'Books > kindle_ebook > Wirtschaft & Finanzen > Unternehmertum', 5, 'Startups', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Wirtschaft & Finanzen > Unternehmertum > Startups > Finanzierung', 'Books > kindle_ebook > Wirtschaft & Finanzen > Unternehmertum > Startups', 6, 'Finanzierung', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Wissenschaft, Technik & Medizin', 'Books > kindle_ebook', 3, 'Wissenschaft, Technik & Medizin', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Wissenschaft, Technik & Medizin > Computer & Technologie', 'Books > kindle_ebook > Wissenschaft, Technik & Medizin', 4, 'Computer & Technologie', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Wissenschaft, Technik & Medizin > Computer & Technologie > Programmierung', 'Books > kindle_ebook > Wissenschaft, Technik & Medizin > Computer & Technologie', 5, 'Programmierung', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Wissenschaft, Technik & Medizin > Computer & Technologie > Programmierung > Python', 'Books > kindle_ebook > Wissenschaft, Technik & Medizin > Computer & Technologie > Programmierung', 6, 'Python', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Wissenschaft, Technik & Medizin > Computer & Technologie > Programmierung > Python > Datenwissenschaft', 'Books > kindle_ebook > Wissenschaft, Technik & Medizin > Computer & Technologie > Programmierung > Python', 7, 'Datenwissenschaft', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Wissenschaft, Technik & Medizin', 'Books > print_kdp_paperback', 3, 'Wissenschaft, Technik & Medizin', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Wissenschaft, Technik & Medizin > Computer & Technologie', 'Books > print_kdp_paperback > Wissenschaft, Technik & Medizin', 4, 'Computer & Technologie', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Wissenschaft, Technik & Medizin > Computer & Technologie > Programmierung', 'Books > print_kdp_paperback > Wissenschaft, Technik & Medizin > Computer & Technologie', 5, 'Programmierung', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Wissenschaft, Technik & Medizin > Computer & Technologie > Programmierung > Python', 'Books > print_kdp_paperback > Wissenschaft, Technik & Medizin > Computer & Technologie > Programmierung', 6, 'Python', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Wissenschaft, Technik & Medizin > Computer & Technologie > Programmierung > Python > Datenwissenschaft', 'Books > print_kdp_paperback > Wissenschaft, Technik & Medizin > Computer & Technologie > Programmierung > Python', 7, 'Datenwissenschaft', true, 1);

-- Summary by marketplace and depth:
-- Amazon.it:
--   Level 2: 2 categories
--   Level 3: 10 categories
--   Level 4: 10 categories
--   Level 5: 10 categories
--   Level 6: 10 categories
--   Level 7: 6 categories
-- Amazon.co.uk:
--   Level 2: 2 categories
--   Level 3: 10 categories
--   Level 4: 10 categories
--   Level 5: 10 categories
--   Level 6: 10 categories
--   Level 7: 6 categories
-- Amazon.de:
--   Level 2: 2 categories
--   Level 3: 10 categories
--   Level 4: 10 categories
--   Level 5: 10 categories
--   Level 6: 10 categories
--   Level 7: 6 categories
-- Amazon.es:
--   Level 2: 2 categories
--   Level 3: 10 categories
--   Level 4: 10 categories
--   Level 5: 10 categories
--   Level 6: 10 categories
--   Level 7: 6 categories
-- Amazon.fr:
--   Level 2: 2 categories
--   Level 3: 10 categories
--   Level 4: 11 categories
--   Level 5: 11 categories
--   Level 6: 11 categories
--   Level 7: 7 categories
--   Level 8: 2 categories
--   Level 9: 1 categories
--   Level 10: 1 categories
--   Level 11: 1 categories
