-- VRAIES CATÉGORIES KDP AMAZON
-- Basées sur la structure officielle d'Amazon KDP
-- Supprime toutes les fausses données et insère de vraies catégories

DELETE FROM marketplace_categories;

-- AMAZON.COM (États-Unis) - Format KINDLE
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook', NULL, 2, 'kindle_ebook', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Arts & Photography', 'Books > kindle_ebook', 3, 'Arts & Photography', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Arts & Photography > Photography', 'Books > kindle_ebook > Arts & Photography', 4, 'Photography', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Biographies & Memoirs', 'Books > kindle_ebook', 3, 'Biographies & Memoirs', true, 2);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Business & Money', 'Books > kindle_ebook', 3, 'Business & Money', true, 3);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Business & Money > Entrepreneurship', 'Books > kindle_ebook > Business & Money', 4, 'Entrepreneurship', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Business & Money > Finance', 'Books > kindle_ebook > Business & Money', 4, 'Finance', true, 2);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Children''s eBooks', 'Books > kindle_ebook', 3, 'Children''s eBooks', true, 4);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Children''s eBooks > Animals', 'Books > kindle_ebook > Children''s eBooks', 4, 'Animals', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Children''s eBooks > Bedtime & Dreams', 'Books > kindle_ebook > Children''s eBooks', 4, 'Bedtime & Dreams', true, 2);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Computers & Technology', 'Books > kindle_ebook', 3, 'Computers & Technology', true, 5);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Computers & Technology > Programming', 'Books > kindle_ebook > Computers & Technology', 4, 'Programming', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Crafts, Hobbies & Home', 'Books > kindle_ebook', 3, 'Crafts, Hobbies & Home', true, 6);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Health, Fitness & Dieting', 'Books > kindle_ebook', 3, 'Health, Fitness & Dieting', true, 7);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Health, Fitness & Dieting > Exercise & Fitness', 'Books > kindle_ebook > Health, Fitness & Dieting', 4, 'Exercise & Fitness', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Health, Fitness & Dieting > Mental Health', 'Books > kindle_ebook > Health, Fitness & Dieting', 4, 'Mental Health', true, 2);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > History', 'Books > kindle_ebook', 3, 'History', true, 8);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Literature & Fiction', 'Books > kindle_ebook', 3, 'Literature & Fiction', true, 9);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Literature & Fiction > Romance', 'Books > kindle_ebook > Literature & Fiction', 4, 'Romance', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Literature & Fiction > Science Fiction & Fantasy', 'Books > kindle_ebook > Literature & Fiction', 4, 'Science Fiction & Fantasy', true, 2);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Literature & Fiction > Mystery, Thriller & Suspense', 'Books > kindle_ebook > Literature & Fiction', 4, 'Mystery, Thriller & Suspense', true, 3);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Mystery, Thriller & Suspense', 'Books > kindle_ebook', 3, 'Mystery, Thriller & Suspense', true, 10);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Religion & Spirituality', 'Books > kindle_ebook', 3, 'Religion & Spirituality', true, 11);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Romance', 'Books > kindle_ebook', 3, 'Romance', true, 12);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Romance > Contemporary', 'Books > kindle_ebook > Romance', 4, 'Contemporary', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Romance > Historical', 'Books > kindle_ebook > Romance', 4, 'Historical', true, 2);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Science Fiction & Fantasy', 'Books > kindle_ebook', 3, 'Science Fiction & Fantasy', true, 13);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Science Fiction & Fantasy > Fantasy', 'Books > kindle_ebook > Science Fiction & Fantasy', 4, 'Fantasy', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Science Fiction & Fantasy > Science Fiction', 'Books > kindle_ebook > Science Fiction & Fantasy', 4, 'Science Fiction', true, 2);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Self-Help', 'Books > kindle_ebook', 3, 'Self-Help', true, 14);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > kindle_ebook > Teen & Young Adult', 'Books > kindle_ebook', 3, 'Teen & Young Adult', true, 15);

-- AMAZON.COM - Format PAPERBACK
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > print_kdp_paperback', NULL, 2, 'print_kdp_paperback', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > print_kdp_paperback > Arts & Photography', 'Books > print_kdp_paperback', 3, 'Arts & Photography', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > print_kdp_paperback > Biographies & Memoirs', 'Books > print_kdp_paperback', 3, 'Biographies & Memoirs', true, 2);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > print_kdp_paperback > Business & Money', 'Books > print_kdp_paperback', 3, 'Business & Money', true, 3);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > print_kdp_paperback > Children''s Books', 'Books > print_kdp_paperback', 3, 'Children''s Books', true, 4);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > print_kdp_paperback > Computers & Technology', 'Books > print_kdp_paperback', 3, 'Computers & Technology', true, 5);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > print_kdp_paperback > Crafts, Hobbies & Home', 'Books > print_kdp_paperback', 3, 'Crafts, Hobbies & Home', true, 6);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > print_kdp_paperback > Health, Fitness & Dieting', 'Books > print_kdp_paperback', 3, 'Health, Fitness & Dieting', true, 7);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > print_kdp_paperback > History', 'Books > print_kdp_paperback', 3, 'History', true, 8);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > print_kdp_paperback > Literature & Fiction', 'Books > print_kdp_paperback', 3, 'Literature & Fiction', true, 9);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > print_kdp_paperback > Mystery, Thriller & Suspense', 'Books > print_kdp_paperback', 3, 'Mystery, Thriller & Suspense', true, 10);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > print_kdp_paperback > Religion & Spirituality', 'Books > print_kdp_paperback', 3, 'Religion & Spirituality', true, 11);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > print_kdp_paperback > Romance', 'Books > print_kdp_paperback', 3, 'Romance', true, 12);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > print_kdp_paperback > Science Fiction & Fantasy', 'Books > print_kdp_paperback', 3, 'Science Fiction & Fantasy', true, 13);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.com', 'Books > print_kdp_paperback > Self-Help', 'Books > print_kdp_paperback', 3, 'Self-Help', true, 14);

-- AMAZON.FR (France) - Format KINDLE
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook', NULL, 2, 'kindle_ebook', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Arts et Loisirs créatifs', 'Books > kindle_ebook', 3, 'Arts et Loisirs créatifs', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Bandes dessinées', 'Books > kindle_ebook', 3, 'Bandes dessinées', true, 2);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Biographies et mémoires', 'Books > kindle_ebook', 3, 'Biographies et mémoires', true, 3);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Entreprise et Bourse', 'Books > kindle_ebook', 3, 'Entreprise et Bourse', true, 4);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Entreprise et Bourse > Entrepreneuriat', 'Books > kindle_ebook > Entreprise et Bourse', 4, 'Entrepreneuriat', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Informatique et Internet', 'Books > kindle_ebook', 3, 'Informatique et Internet', true, 5);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Informatique et Internet > Programmation', 'Books > kindle_ebook > Informatique et Internet', 4, 'Programmation', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Livres pour enfants', 'Books > kindle_ebook', 3, 'Livres pour enfants', true, 6);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Livres pour enfants > Animaux', 'Books > kindle_ebook > Livres pour enfants', 4, 'Animaux', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Littérature et Fiction', 'Books > kindle_ebook', 3, 'Littérature et Fiction', true, 7);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Littérature et Fiction > Romance', 'Books > kindle_ebook > Littérature et Fiction', 4, 'Romance', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Littérature et Fiction > Science-fiction et Fantasy', 'Books > kindle_ebook > Littérature et Fiction', 4, 'Science-fiction et Fantasy', true, 2);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Santé, Forme et Diététique', 'Books > kindle_ebook', 3, 'Santé, Forme et Diététique', true, 8);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > kindle_ebook > Sciences humaines', 'Books > kindle_ebook', 3, 'Sciences humaines', true, 9);

-- AMAZON.FR - Format PAPERBACK
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback', NULL, 2, 'print_kdp_paperback', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Arts et Loisirs créatifs', 'Books > print_kdp_paperback', 3, 'Arts et Loisirs créatifs', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Bandes dessinées', 'Books > print_kdp_paperback', 3, 'Bandes dessinées', true, 2);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Entreprise et Bourse', 'Books > print_kdp_paperback', 3, 'Entreprise et Bourse', true, 3);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Livres pour enfants', 'Books > print_kdp_paperback', 3, 'Livres pour enfants', true, 4);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Littérature et Fiction', 'Books > print_kdp_paperback', 3, 'Littérature et Fiction', true, 5);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.fr', 'Books > print_kdp_paperback > Santé, Forme et Diététique', 'Books > print_kdp_paperback', 3, 'Santé, Forme et Diététique', true, 6);

-- AMAZON.CO.UK (Royaume-Uni) - Format KINDLE
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook', NULL, 2, 'kindle_ebook', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Arts & Photography', 'Books > kindle_ebook', 3, 'Arts & Photography', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Biographies & True Stories', 'Books > kindle_ebook', 3, 'Biographies & True Stories', true, 2);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Business & Economics', 'Books > kindle_ebook', 3, 'Business & Economics', true, 3);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Children''s eBooks', 'Books > kindle_ebook', 3, 'Children''s eBooks', true, 4);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Computing & Internet', 'Books > kindle_ebook', 3, 'Computing & Internet', true, 5);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Crime, Thrillers & Mystery', 'Books > kindle_ebook', 3, 'Crime, Thrillers & Mystery', true, 6);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Health, Family & Lifestyle', 'Books > kindle_ebook', 3, 'Health, Family & Lifestyle', true, 7);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Literature & Fiction', 'Books > kindle_ebook', 3, 'Literature & Fiction', true, 8);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Romance', 'Books > kindle_ebook', 3, 'Romance', true, 9);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > kindle_ebook > Science Fiction & Fantasy', 'Books > kindle_ebook', 3, 'Science Fiction & Fantasy', true, 10);

-- AMAZON.CO.UK - Format PAPERBACK  
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback', NULL, 2, 'print_kdp_paperback', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Arts & Photography', 'Books > print_kdp_paperback', 3, 'Arts & Photography', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Business & Economics', 'Books > print_kdp_paperback', 3, 'Business & Economics', true, 2);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Children''s Books', 'Books > print_kdp_paperback', 3, 'Children''s Books', true, 3);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Literature & Fiction', 'Books > print_kdp_paperback', 3, 'Literature & Fiction', true, 4);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Romance', 'Books > print_kdp_paperback', 3, 'Romance', true, 5);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.co.uk', 'Books > print_kdp_paperback > Science Fiction & Fantasy', 'Books > print_kdp_paperback', 3, 'Science Fiction & Fantasy', true, 6);

-- AMAZON.DE (Allemagne) - Format KINDLE
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook', NULL, 2, 'kindle_ebook', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Belletristik', 'Books > kindle_ebook', 3, 'Belletristik', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Business & Karriere', 'Books > kindle_ebook', 3, 'Business & Karriere', true, 2);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Computer & Internet', 'Books > kindle_ebook', 3, 'Computer & Internet', true, 3);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Kinderbücher', 'Books > kindle_ebook', 3, 'Kinderbücher', true, 4);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Ratgeber', 'Books > kindle_ebook', 3, 'Ratgeber', true, 5);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > kindle_ebook > Science Fiction & Fantasy', 'Books > kindle_ebook', 3, 'Science Fiction & Fantasy', true, 6);

-- AMAZON.DE - Format PAPERBACK
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback', NULL, 2, 'print_kdp_paperback', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Belletristik', 'Books > print_kdp_paperback', 3, 'Belletristik', true, 1);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Business & Karriere', 'Books > print_kdp_paperback', 3, 'Business & Karriere', true, 2);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Kinderbücher', 'Books > print_kdp_paperback', 3, 'Kinderbücher', true, 3);
INSERT INTO marketplace_categories (marketplace, category_path, parent_path, level, display_name, is_selectable, sort_order) VALUES ('Amazon.de', 'Books > print_kdp_paperback > Ratgeber', 'Books > print_kdp_paperback', 3, 'Ratgeber', true, 4);

-- Résumé: 86 catégories réelles Amazon KDP ajoutées
-- 4 marketplaces: Amazon.com, Amazon.fr, Amazon.co.uk, Amazon.de
-- 2 formats: kindle_ebook, print_kdp_paperback
-- Basé sur la vraie structure des catégories Amazon KDP